### ISSUE TITLE
Drozone returning array_filter() error

### ISSUE THREAD

**Issue by logifloor** [Laravel-Backpack/medialibrary-uploaders#22]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/772

<div type='discussions-op-text'>

<sup>Originally posted by **logifloor** December  1, 2023</sup>
I'm struggling with Dropzone uploads when using the Spatie media library addon.  All is working well until I try and submit a form without any uploads (other fields text/date etc populated).  I don't want to 'require' and upload because sometimes not necessary for this application, however, after extensive debugging, I can't find a solution to array_filter(): Argument Laravel-Backpack/community-forum#1 ($array) must be of type array, null given, when the files field is submitted empty.  Anybody else come across this?</div>

**Comment by pxpm** [comment]
Thanks for the report @logifloor and sorry for the bad experience. 

I've just fixed it in #26 🙏 

Thanks @karandatwani92 for confirming the issue and providing an easy to read issue history in this thread 🙏 

Cheers

**Comment by logifloor** [comment]
Just a quick follow on from this, you (or I at least), now have to ensure I send 'something' with withMedia(), or it returns an empty array error.  I.e. withMedia('');

**Comment by pxpm** [comment]
Humm sorry the bad experience 🙏 . That shouldn't be happening, thanks for the report. 

I've just pushed a fix for it in 1.0.3, you can get it with a `composer update backpack/medialibrary-uploaders`

Cheers
