### ISSUE TITLE
[Bug] Incompatible with last version of spatie/laravel-medialibrary

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/medialibrary-uploaders#28]
# Bug report

### What I did

I create a new project with  `"spatie/laravel-medialibrary": "^11.0.0"`

### What I expected to happen

Install this pacakge and use medialibrary + backpack

### What happened
This pagages is only compatible with version ^10.7
![image](https://github.com/Laravel-Backpack/medialibrary-uploaders/assets/20278289/3d297098-ebfb-43a8-bd68-83c132eccb92)

### What I've already tried to fix it

For now i don't install this package because i don't want to downgrade spatie/laravel-medialibrary

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.2.1 (cli) (built: Jan 13 2023 10:42:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.45.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.3
backpack/crud: 6.6.3
backpack/generators: v4.0.3
backpack/pro: 2.1.7
backpack/theme-tabler: 1.2.0
```

**Comment by pxpm** [comment]
It should now support v 11.3 (where Laravel v11 support was added).
