### ISSUE TITLE
MediaUploader / getMediaIdentifier() method. It does not retrieve correctly conversions

### ISSUE THREAD

**Issue by manfield** [Laravel-Backpack/medialibrary-uploaders#36]
# Bug report

if you have several conversion for your media, and you have more than one media in your CrudController, they don't display correctly.

### What I did

If you create two image type element in your CrudController and try to show, for each of them a different conversion, you will see the original image as preview

![image](https://github.com/user-attachments/assets/10dcca59-d51c-4917-9b76-a0344bb77917)

### What I expected to happen

I expect to see, for each of them the correct conversion:

![image](https://github.com/user-attachments/assets/1cb9ae75-6d90-4019-9acc-ee71ba795b83)

### What happened

The issue is in the getMediaIdentifier.
Developer expects to obtain an array of values from array_filter, while he obtains new array with new keys.
The solution is flatten to values the array, prepending array_values.

**Comment by jcastroa87** [comment]
Hello @manfield 

Thanks, I see the PR. Let continue the discussion there.

Cheers.
